- name: Overview
  href: index.md
- name: Quickstart
  href: quickstart.md
- name: Tutorials
  href: tutorials.md
  items:
  - name: Building Blocks
    href: building-blocks.md
  - name: Explore Automation
    href: explore-automation.md
  - name: Get Started with Players and Tournaments
    href: get-started-with-players-and-tournaments.md
  - name: Getting Started with PlayFab
    href: getting-started-with-playfab.md
  - name: Set up your game's in-game economy
    href: set-up-your-games-in-game-economy.md
  - name: Try out content management
    href: try-out-content-management.md
