### YamlMime:YamlDocument
documentType: LandingData
title: "PlayFab Automation Features"
metadata:
  title: "PlayFab Automation Features"
  author: v-thopra  
  description: Landing page for PlayFab Automation features.
  ms.author: v-thopra
  ms.date: 11/13/2018
  ms.topic: landing-page
  ms.prod: playfab  
  keywords: playfab, automation
  ms.localizationpriority: medium
sections:
- items:
  - type: list
    style: cards
    className: cardsF
    columns: 3
    items:
    - image:
        src: "/gaming/playfab/features/media/feature-cloudscript.svg"
        text: "PlayFab Automation Features - CloudScript card image"        
      title: "CloudScript"
      html: "<p style='color: #7f7f7f'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><p><a href='/gaming/playfab/features/automation/cloudscript/'>Overview</a></p><p><a href='/gaming/playfab/features/automation/cloudscript/quickstart'>Quickstart</a></p><p><a href='/gaming/playfab/features/automation/cloudscript/tutorials'>Tutorials</a></p>"
    - image:
        src: "/gaming/playfab/features/media/feature-playstream.svg"
        text: "PlayFab Automation Features - PlayStream card image"        
      title: "PlayStream"
      html: "<p style='color: #7f7f7f'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><p><a href='/gaming/playfab/features/automation/playstream-events/'>Overview</a></p><p><a href='/gaming/playfab/features/automation/playstream-events/quickstart'>Quickstart</a></p><p><a href='/gaming/playfab/features/automation/playstream-events/tutorials'>Tutorials</a></p>"
    - image:
        src: "/gaming/playfab/features/media/feature-actions-rules.svg"
        text: "PlayFab Automation Features - Actions & Rules card image"        
      title: "Actions &amp; Rules"
      html: "<p style='color: #7f7f7f'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><p><a href='/gaming/playfab/features/automation/actions-rules/'>Overview</a></p><p><a href='/gaming/playfab/features/automation/actions-rules/quickstart'>Quickstart</a></p><p><a href='/gaming/playfab/features/automation/actions-rules/tutorials'>Tutorials</a></p>"
    - image:
        src: "/gaming/playfab/features/media/feature-scheduled-tasks.svg"
        text: "PlayFab Automation Features - Scheduled Tasks card image"        
      title: "Scheduled Tasks"
      html: "<p style='color: #7f7f7f'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><p><a href='/gaming/playfab/features/automation/scheduled-tasks/'>Overview</a></p><p><a href='/gaming/playfab/features/automation/scheduled-tasks/quickstart'>Quickstart</a></p>"
