- name: Game Manager
  href: index.md
  items:
  - name: Quickstart
    href: /playFab/features/config/gamemanager/quickstart.md
  - name: Tutorials
    href: /playFab/features/config/gamemanager/tutorials.md